coverage:
  status:
    project:
      api:
        paths:
          - packages/apollos-api/*
      mobile:
        paths:
          - packages/ConferenceApp/*
comment:
  layout: "reach, diff, files"
  behavior: once